name: .NET Continuous Integration

on:
  # Run on code pushes and pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest  # Use a Windows environment for .NET projects

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0  # Match the project's target framework

    # Step 3: Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Step 4: Build the project
    - name: Build Project
      run: dotnet build --no-restore --configuration Debug

    # Step 5: Run Tests
    - name: Run Tests
      run: dotnet test --no-build --configuration Debug --logger:"trx;LogFileName=TestResults.trx"
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    # Step 6: Publish Test Results
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/TestResults.trx'

    # Step 7: Upload Code Coverage Report (optional)
    - name: Upload Coverage Report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: '**/coverage.cobertura.xml'
