name: .NET Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    # Step 3: Navigate to the project directory
    - name: Change Directory
      working-directory: ./TestProjectXunit4CICDAndYAML
      run: pwd  # Optional, to confirm the working directory

    # Step 4: Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Step 5: Build the project
    - name: Build Project
      run: dotnet build --no-restore --configuration Debug

    # Step 6: Run tests
    - name: Run Tests
      run: dotnet test --no-build --configuration Debug --logger:"trx;LogFileName=TestResults.trx"

    # Step 7: Publish test results
    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/TestResults.trx'
